version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    environment:
      - TZ='Eurpoe/London'
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    stdin_open: true
    tty: true
    ports:
      - 1883:1883
      - 9001:9001
    hostname: mosquitto

  FlaskServerWK1:
    image: tabongazifodyacap/ab_flaskwk1_virtfansim:latest
    container_name: FlaskServerWK1
    environment:
      - TZ='Eurpoe/London'
    stdin_open: true
    tty: true
    ports:
      - 5000:5000

  grafana:
    image: grafana/grafana-oss:9.3.1
    container_name: grafana
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana:rw
    stdin_open: true
    tty: true
    user: "472"
    ports:
      - 3000:3000
    hostname: grafana

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    volumes:
      - ./influxdb2/data:/var/lib/influxdb2
      - ./influxdb2/config:/etc/influxdb2
    env_file:
      - .env
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=airbus
      - INFLUXDB_ADMIN_PASSWORD=colliderspace
      - INFLUXDB_ADMIN_HTTPS_ENABLED
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 8086:8086
    hostname: influxdb
